import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Snapshots taken before refactors — not part of the app.
    "_backups/**",
    // Generated by `prisma skills sync`, not application code.
    ".agents/**",
    ".cursor/**",
    ".devin/**",
  ]),
]);

export default eslintConfig;
